global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text.Json;
global using System.Threading.Tasks;
global using Ardalis.GuardClauses;
global using Core.Entities;
global using Core.Entities.Identity;
global using Core.Entities.OrderAggregate;
global using Core.Interfaces;
global using Core.Specifications;
global using Infrastructure.Data.DTOs;
global using Infrastructure.Extensions;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Query;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using StackExchange.Redis;
global using Stripe;
global using Product = Core.Entities.Product;
global using File = System.IO.File;